### ISSUE TITLE
图片size宽度小于屏幕宽度是动画结束导致图片瞬移问题

### ISSUE THREAD

**Issue by teamo1017** [Heiyuan/BigImageBrowse#1]
问题文件：`BrowseImageScrollView.m`
问题方法：`- (void)setImage:(UIImage *)image` 第70行

解决方案：问题方法最后加上 `_imageView.center = self.center;`

**Comment by Heiyuan** [comment]
可以..你可以 克隆到本地然后在推上来..

**Comment by Heiyuan** [comment]
已修复,
